apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2026-02-11T00:48:59Z"
  generation: 3
  labels:
    app: openshift-demo
  name: openshift-demo
  namespace: bloodfallen-dev
  resourceVersion: "5754019143"
  uid: 853c077c-592f-457a-bc06-2adfe7b8488c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: openshift-demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: openshift-demo
    spec:
      containers:
      - name: openshift-demo
        image: default-route-openshift-image-registry.apps.rm1.0a51.p1.openshiftapps.com/bloodfallen-dev/openshift-demo:1.1
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: demo-app-config
        - secretRef:
            name: demo-app-secret
        volumeMounts:
        - name: app-data
          mountPath: /data
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File

      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: demo-app-pvc
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2026-02-11T00:49:13Z"
    lastUpdateTime: "2026-02-11T00:49:13Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2026-02-11T00:48:59Z"
    lastUpdateTime: "2026-02-11T02:46:35Z"
    message: ReplicaSet "openshift-demo-8675bd68d5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
